clientes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.lista_cliente, name='lista_cliente'),
    path('clientes/', views.lista_cliente, name='lista_cliente'),  # URL para listar clientes
    path('novo/', views.cria_cliente, name='cria_cliente'),
    path('editar/<int:pk>/', views.edita_cliente, name='edita_cliente'),
    path('deletar/<int:pk>/', views.deleta_cliente, name='deleta_cliente'),
]

empresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),
    path('', lambda request: redirect('lista_cliente'), name='clientes'),
    path('funcionarios/', include('funcionarios.urls'), name='funcionarios')
]

funcionarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.lista_funcionarios, name='lista_funcionarios'),
    path('funcionarios/', views.lista_funcionarios, name='lista_funcionarios'),  # URL para listar clientes
    path('novo/', views.cria_funcionario, name='cria_funcionario'),
    path('editar/<int:pk>/', views.edita_funcionario, name='edita_funcionario'),
    path('deletar/<int:pk>/', views.deleta_funcionario, name='deleta_funcionario'),
]

clientes/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length = 100)
    endereco = models.TextField()
    cpf = models.CharField(max_length = 14, unique=True)
    data_nascimento = models.DateField()
    
    def __str__(self):
        return self.nome

funcionarios/models.py
from django.db import models

class Funcionario(models.Model):
    nome = models.CharField(max_length = 100)
    edv = models.CharField(max_length = 8, unique = True)
    cargo = models.CharField(max_length = 100)
    setor = models.CharField(max_length = 100)
    endereco = models.TextField()
    horario_entrada = models.TimeField(blank=False)
    horario_saida = models.TimeField(blank=False)
    data_admissao = models.DateField(blank=False)
    
    def __str__(self):
        return self.nome

clientes/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'endereco', 'cpf', 'data_nascimento']

funcionarios/forms.py
from django import forms
from .models import Funcionario

class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        fields = ['nome', 'edv', 'cargo', 'setor', 'endereco', 'horario_entrada', 'horario_saida','data_admissao']

clientes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cliente
from .forms import ClienteForm

def lista_cliente(request):
    clientes = Cliente.objects.all()
    return render(request, 'clientes/lista_cliente.html', {'clientes': clientes})

def cria_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_cliente')
    else:
        form = ClienteForm()
    return render(request, 'clientes/cria_cliente.html', {'form': form})

def edita_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('lista_cliente')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'clientes/edita_cliente.html', {'form':form})
    
def deleta_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    cliente.delete()
    return redirect('lista_cliente')

funcionarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Funcionario
from .forms import FuncionarioForm

def lista_funcionarios(request):
    funcionarios = Funcionario.objects.all()
    return render(request, 'funcionarios/lista_funcionarios.html', {'funcionarios': funcionarios})

def cria_funcionario(request):
    if request.method == 'POST':
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_funcionarios')
    else:
        form = FuncionarioForm()
    print(form)
    return render(request, 'funcionarios/cria_funcionario.html', {'form': form})

def edita_funcionario(request, pk):
    funcionario = get_object_or_404(Funcionario, pk=pk)
    if request.method == 'POST':
        form = FuncionarioForm(request.POST, instance=funcionario)
        if form.is_valid():
            form.save()
            return redirect('lista_funcionarios')
    else:
        form = FuncionarioForm(instance=funcionario)
    return render(request, 'funcionarios/edita_funcionario.html', {'form': form})

def deleta_funcionario(request, pk):
    funcionario = get_object_or_404(Funcionario, pk=pk)
    funcionario.delete()
    return redirect('lista_funcionarios')

clientes/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SISTEMA DE CLIENTES</title>
    <!-- Inclua links para os arquivos CSS do Bootstrap ou de outros estilos -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous">   
</head>
<body>
    <header>
        <!-- Cabeçalho com o logotipo e menu -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Título centralizado -->
            <h1 class="navbar-brand title">ROBERT BOSCH</h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lista_cliente'%}">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lista_funcionarios'%}">Funcionários</a>
                    </li>
                    <!-- Adicione mais itens de menu conforme necessário -->
                </ul>
            </div>
        </nav>
    </header>
    <div class="container mt-4">
        <!-- Conteúdo da página -->
        {% block content %}{% endblock %}
    </div>

    <footer class="mt-4">
        <!-- Rodapé do site -->
        <div class="text-center">
            © 2024 PROJETO CRUD COM DJANGO - DTA BOSCH. Todos os direitos reservados.
        </div>
    </footer>
    <!-- Inclua links para os arquivos JavaScript do Bootstrap ou de outros scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

clientes/templates/clientes/cria_cliente.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Criar Novo Cliente</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'lista_cliente' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

clientes/templates/clientes/deleta_cliente.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Confirmação de Exclusão</h1>
    <p>Tem certeza de que deseja excluir o cliente "{{ cliente.nome }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Sim, Excluir</button>
        <a href="{% url 'lista_cliente' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

clientes/templates/clientes/edita_cliente.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Editar Cliente</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'lista_cliente' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

clientes/templates/clientes/lista_cliente.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Lista de Clientes</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Endereço</th>
                <th>CPF</th>
                <th>Data de Nascimento</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
            <tr>
                <td>{{ cliente.id }}</td>
                <td>{{ cliente.nome }}</td>
                <td>{{ cliente.endereco }}</td>
                <td>{{ cliente.cpf }}</td>
                <td>{{ cliente.data_nascimento }}</td>
                <td>
                    <a href="{% url 'edita_cliente' cliente.id %}" class="btn btn-primary">Editar</a>
                    <a href="{% url 'deleta_cliente' cliente.id %}" class="btn btn-danger">Excluir</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'cria_cliente' %}" class="btn btn-success">Novo Cliente</a>
</div>
{% endblock %}

funcionarios/templates/funcionarios/cria_funcionario.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'funcionarios/css/style.css' %}" />
<div class="container">
    <h1>Criar Novo Funcionário</h1>
    <form method="post">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}

        <div id="inputs">
            <div>
                <label for="id_nome">Nome:</label>
                <input class="inputBox" type="text" name="nome" maxlength="100" required id="id_nome"
                    placeholder="Insira seu nome" />
            </div>

            <div>
                <label for="id_edv">EDV:</label>
                <input type="text" name="edv" maxlength="8" required id="id_edv" placeholder="Insira seu EDV" />
            </div>

            <div>
                <label for="id_cargo">Cargo:</label>
                <input type="text" name="cargo" maxlength="100" required id="id_cargo" placeholder="Insira seu cargo" />
            </div>

            <div>
                <label for="id_setor">Setor:</label>
                <input type="text" name="setor" maxlength="100" required id="id_setor" placeholder="Insira seu setor" />
            </div>

            <div>
                <label for="id_endereco">Endereço:</label>
                <input type="text" name="endereco" maxlength="100" required id="id_endereco"
                    placeholder="Insira seu endereço" />
            </div>

            <div>
                <label for="id_horario_entrada">Horário de entrada:</label>
                <input type="time" name="horario_entrada" required id="id_horario_entrada"
                    placeholder="Insira o horário de entrada" />
            </div>

            <div>
                <label for="id_horario_saida">Horário de saída:</label>
                <input type="time" name="horario_saida" required id="id_horario_saida" placeholder="" />
            </div>

            <div>
                <label for="id_data_admissao">Data de admissão:</label>
                <input type="date" name="data_admissao" required id="id_data_admissao" />
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'lista_funcionarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

funcionarios/templates/funcionarios/deleta_funcionario.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Confirmação de Exclusão</h1>
    <p>Tem certeza de que deseja excluir o cliente "{{ funcionario.nome }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Sim, Excluir</button>
        <a href="{% url 'lista_funcionarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

funcionarios/templates/funcionarios/edita_funcionario.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Editar Funcionário</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'lista_funcionarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

funcionarios/templates/funcionarios/lista_funcionarios.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Lista de Funcionários</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>EDV</th>
                <th>Cargo</th>
                <th>Setor</th>
                <th>Endereço</th>
                <th>Horário de entrada</th>
                <th>Horário de saída</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for funcionario in funcionarios %}
            <tr>
                <td>{{ funcionario.id }}</td>
                <td>{{ funcionario.nome }}</td>
                <td>{{ funcionario.edv }}</td>
                <td>{{ funcionario.cargo }}</td>
                <td>{{ funcionario.setor }}</td>
                <td>{{ funcionario.endereco }}</td>
                <td>{{ funcionario.horario_entrada }}</td>
                <td>{{ funcionario.horario_saida }}</td>
                <td>{{ funcionario.data_admissao }}</td>
                <td>
                    <a href="{% url 'edita_funcionario' funcionario.id %}" class="btn btn-primary">Editar</a>
                    <a href="{% url 'deleta_funcionario' funcionario.id %}" class="btn btn-danger">Excluir</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'cria_funcionario' %}" class="btn btn-success">Novo Funcionário</a>
</div>
{% endblock %}